source 'https://rubygems.org'
gem 'activesupport', '>= 0'
gem 'chronic', '>= 0'
gem 'faraday', '>= 0'
gem 'faraday-http-cache', '>= 0'
gem 'faraday_middleware', '>= 0'
gem 'hashie', '>= 0'
gem 'hurley', '>= 0'
gem 'json_color', '>= 0'
gem 'mechanize', '>= 0'
gem 'oauth2', '>= 0'
gem 'rest-client', '>= 0'
gem 'rails', '~> 2.3.0'