name: Check
on:
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:

  check:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: RUBY_VERSION
          bundler: none

      - name: Install bundler
        run: gem install bundler -v BUNDLER_VERSION

      - name: Try to create lockfile
        run: bundle _BUNDLER_VERSION_ lock >> $GITHUB_STEP_SUMMARY
